name: Deploy Static Website to S3

# Trigger workflow when you push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials (v2)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   # Change region if your S3 bucket is in another region

    # Step 3: Debug: Check if AWS credentials are valid
    - name: Check AWS Identity
      run: aws sts get-caller-identity

    # Step 4: Deploy static files to S3
    - name: Deploy to S3
      run: aws s3 sync . s3://myprojectgitmanos3 --delete

